# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 20:44
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogitems', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dealer',
            new_name='DealerPage',
        ),
        migrations.AlterField(
            model_name='catalogitempage',
            name='item_catalog',
            field=wagtail.wagtailcore.fields.StreamField((('catalog', wagtail.wagtailcore.blocks.PageChooserBlock(target_model='catalogitems.CatalogPage')),)),
        ),
        migrations.AlterField(
            model_name='catalogitempage',
            name='item_composer',
            field=wagtail.wagtailcore.fields.StreamField((('composer', wagtail.wagtailcore.blocks.PageChooserBlock(target_model='catalogitems.ComposerPage')),)),
        ),
        migrations.AlterField(
            model_name='catalogitempage',
            name='item_dealer',
            field=wagtail.wagtailcore.fields.StreamField((('dealer', wagtail.wagtailcore.blocks.PageChooserBlock(target_model='catalogitems.DealerPage')),)),
        ),
    ]
