# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 20:47
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogitems', '0002_auto_20170425_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitempage',
            name='place',
        ),
        migrations.AddField(
            model_name='catalogitempage',
            name='item_places',
            field=wagtail.wagtailcore.fields.StreamField((('place', wagtail.wagtailcore.blocks.PageChooserBlock(target_model='catalogitems.PlacePage')),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogitempage',
            name='item_type',
            field=wagtail.wagtailcore.fields.StreamField((('item_type', wagtail.wagtailcore.blocks.PageChooserBlock(target_model='catalogitems.ItemTypePage')),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogitempage',
            name='piece_title',
            field=wagtail.wagtailcore.fields.StreamField((('piece_title', wagtail.wagtailcore.blocks.PageChooserBlock(target_model='catalogitems.PieceTitlePage')),), blank=True, null=True),
        ),
    ]
