# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('catalogitems', '0003_auto_20170425_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorOrResponsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('optional_title', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTypeOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PieceTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecipientOrDedicatee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('optional_title', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='authororresponsiblepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='catalogpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='composerpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='dealerpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='itemtypepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='piecetitlepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='placepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='recipientordedicateepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='catalogitempage',
            name='item_places',
        ),
        migrations.RemoveField(
            model_name='catalogitempage',
            name='piece_title',
        ),
        migrations.AlterField(
            model_name='catalogitempage',
            name='item_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogitems.Catalog'),
        ),
        migrations.AlterField(
            model_name='catalogitempage',
            name='item_composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogitems.Composer'),
        ),
        migrations.AlterField(
            model_name='catalogitempage',
            name='item_dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogitems.Dealer'),
        ),
        migrations.RemoveField(
            model_name='catalogitempage',
            name='item_type',
        ),
        migrations.DeleteModel(
            name='AuthorOrResponsiblePage',
        ),
        migrations.DeleteModel(
            name='CatalogPage',
        ),
        migrations.DeleteModel(
            name='ComposerPage',
        ),
        migrations.DeleteModel(
            name='DealerPage',
        ),
        migrations.DeleteModel(
            name='ItemTypePage',
        ),
        migrations.DeleteModel(
            name='PieceTitlePage',
        ),
        migrations.DeleteModel(
            name='PlacePage',
        ),
        migrations.DeleteModel(
            name='RecipientOrDedicateePage',
        ),
        migrations.AddField(
            model_name='itemtypeorderable',
            name='a_record',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_types', to='catalogitems.CatalogItemPage'),
        ),
        migrations.AddField(
            model_name='itemtypeorderable',
            name='a_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogitems.ItemType', verbose_name='Item Type'),
        ),
        migrations.AddField(
            model_name='catalogitempage',
            name='item_type',
            field=models.ManyToManyField(blank=True, through='catalogitems.ItemTypeOrderable', to='catalogitems.ItemType'),
        ),
    ]
