# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogitems', '0004_auto_20170426_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorOrResponsibleOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('an_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogitems.AuthorOrResponsible', verbose_name='An Item Author Or Responsible ')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PieceTitleOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('a_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogitems.PieceTitle', verbose_name='A Title')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PlaceOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('a_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogitems.Place', verbose_name='A Place')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RecipientOrDedicateeOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('a_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogitems.RecipientOrDedicatee', verbose_name='An Item Author Or Responsible ')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='catalogitempage',
            name='item_type',
        ),
        migrations.AddField(
            model_name='recipientordedicateeorderable',
            name='recipient_author',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_recipientordedicatees', to='catalogitems.CatalogItemPage'),
        ),
        migrations.AddField(
            model_name='placeorderable',
            name='place_record',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_places', to='catalogitems.CatalogItemPage'),
        ),
        migrations.AddField(
            model_name='piecetitleorderable',
            name='piece_record',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_titles', to='catalogitems.CatalogItemPage'),
        ),
        migrations.AddField(
            model_name='authororresponsibleorderable',
            name='author_record',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_authororesposibles', to='catalogitems.CatalogItemPage'),
        ),
    ]
