# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogitems', '0005_auto_20170426_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipientordedicateeorderable',
            old_name='recipient_author',
            new_name='recipient_record',
        ),
    ]
