# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 20:41
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogitems', '0006_auto_20170426_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitempage',
            name='related_items',
            field=wagtail.wagtailcore.fields.StreamField((('related_item', wagtail.wagtailcore.blocks.PageChooserBlock(target_model='catalogitems.CatalogItemPage')),), blank=True, null=True),
        ),
    ]
