# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogitems', '0007_catalogitempage_related_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipientordedicatee',
            name='optional_title',
        ),
    ]
